"""
Product model — represents a craft listing in the marketplace.
"""

from pydantic import BaseModel
from typing import Optional
from datetime import datetime


class ProductBase(BaseModel):
    """Shared product fields."""
    title: Optional[str] = None
    description: Optional[str] = None
    cultural_story: Optional[str] = None
    price: float
    category: Optional[str] = None
    tags: Optional[list[str]] = []
    image_url: Optional[str] = None
    audio_url: Optional[str] = None


class ProductCreate(BaseModel):
    """Fields submitted during product creation (before AI processing)."""
    artisan_id: str
    price: float
    image_url: Optional[str] = None
    audio_url: Optional[str] = None


class ProductUpdate(BaseModel):
    """Fields that can be updated after AI generation or manual edit."""
    title: Optional[str] = None
    description: Optional[str] = None
    cultural_story: Optional[str] = None
    price: Optional[float] = None
    category: Optional[str] = None
    tags: Optional[list[str]] = None
    seo_keywords: Optional[list[str]] = None
    status: Optional[str] = None  # "draft", "published"
    is_published: Optional[bool] = None
    is_available: Optional[bool] = None
    raw_voice_text: Optional[str] = None
    ai_generated: Optional[bool] = None


class ProductResponse(ProductBase):
    """Full product response including metadata."""
    product_id: str
    artisan_id: str
    status: str = "draft"
    is_published: bool = False
    created_at: datetime

    class Config:
        from_attributes = True


class AIGeneratedContent(BaseModel):
    """Content generated by the AI pipeline."""
    title: str
    short_description: str
    full_description: str
    cultural_story: str
    category: str
    tags: list[str]
    seo_keywords: list[str]
